---
parameters:
- name: IMAGE
  value: quay.io/carbonin/config-image-server
- name: TAG
  value: latest
- name: BMC_ADDRESS
  required: true
- name: BMC_USER
  value: admin
- name: BMC_PASSWORD
  value: password
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: assisted-installer
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: config-image-server
  spec:
    to:
      kind: Service
      name: config-image-server
    port:
      targetPort: config-server
- apiVersion: v1
  kind: Service
  metadata:
    name: config-image-server
    labels:
      name: config-image-server
  spec:
    ports:
    - port: 8080
      protocol: TCP
      name: config-server
    selector:
      name: config-image-server
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: config-image-server
  spec:
    selector:
      matchLabels:
        name: config-image-server
    template:
      metadata:
        labels:
          name: config-image-server
      spec:
        containers:
        - name: config-image-server
          image: ${IMAGE}:${TAG}
          ports:
          - name: config-server
            containerPort: 8080
          env:
          - name: BMC_ADDRESS
            value: ${BMC_ADDRESS}
          - name: BMC_PASSWORD
            value: ${BMC_PASSWORD}
          - name: BMC_USER
            value: ${BMC_USER}
          - name: DATA_DIR
            value: "/data"
